// THIS SCRIPT WAS CREATED USING GENERATIVE AI

// PWSE English quote resources v1.0. Extracted from namespace 0x840500, language 0xD0E.
// Ordinary selection: CONFIRMED by decompilation; known examples matched runtime/resources.
// Base preview only: special-character/status override helpers remain unresolved.
(function(global){
'use strict';
const ordinary = Object.freeze({
  "f001": "Give me any order you want. I'll make it happen.",
  "f002": "I left my hometown and haven't looked back.",
  "f003": "I'm good to go as long as I have three square meals.",
  "f004": "I'm going to be taking a good look at your command style.",
  "f005": "Male, female... I heard it doesn't matter out here. I heard you'll use us just the same.",
  "f006": "What's your sidearm of choice? A handgun? Or, maybe a submachine gun?",
  "f007": "I'm so sleepy...",
  "f008": "I'll go berserk if my pay's late.",
  "f009": "Just so you know, I'm only here to pay for my kid brother's education, so spare me the cheesy battlefield romance.",
  "f010": "I caught a whiff of an ocean breeze...",
  "f011": "I won't disappoint you, and that's a promise.",
  "f012": "Can't say I'm impressed by anyone here. I guess I'll have to help you out.",
  "f013": "I used to work in a kitchen. Whether it's guns or knives, just leave it to me.",
  "f014": "Let's square off in the ring next chance we have!",
  "f015": "You do have a good medic, don't you? I mean, people die all the time from minor wounds that get infected. You gotta have a good medic.",
  "f016": "My mom was a fighter pilot.",
  "f017": "I don't choose sides. Whoever needs me, that's where I go.",
  "f018": "I'm prepared to die for you!",
  "f019": "I like that look you have in your eyes, Boss!",
  "f020": "I majored in quantum mechanics, and I'm continuing my studies on the side.",
  "f021": "The sky's so blue again today.",
  "f022": "Did you know that 65% of the world's top assassins are women?",
  "f023": "I may not look it, but I took third in a national weightlifting tournament.",
  "f024": "I have a proven track record. No matter the mission, I'll deliver the goods.",
  "f025": "Today is your lucky day. I'm going to join your unit!",
  "f026": "My mother's in the hospital, so send me somewhere the pay's good. I don't care how dangerous it is.",
  "f027": "Our rations include tea and scones, right?",
  "f028": "So you're that Boss I heard about. It's an honor to meet you.",
  "f029": "I smelled gallo pinto earlier. Is that what's for dinner?",
  "f030": "I heard you train with unlimited live fire. That true?",
  "f031": "If you're out of rations, why not have a snack instead? Like curry - mmm, can't get enough!",
  "f032": "The more you use a certain weapon, the more of its natural power will be unleashed. Interesting... I'll have to remember that.",
  "f033": "I don't like my hair to get messed up, but for you, I'll go fight.",
  "f034": "Getting the highest clear rank means not killing, not being seen, and moving quickly. You can do it, Boss!",
  "f035": "There's more than one way to \"neutralize\" somebody, right, Boss? You can knock 'em out with a stun rod, or put 'em to sleep with a tranq gun, or sneak up from behind and hold 'em up...",
  "f036": "If it's taking too long to aim, switch to AUTO AIM. That's what's kept me alive all this time.",
  "f037": "The \"3 Slot\" weapon select takes some getting used to, but once you get the hang of it, it's a cinch. And boy, is it deadly!",
  "f038": "There's nothing like sleep for recovering LIFE! And if you can't sleep, lie down and stay still! Isn't that right, sir?",
  "f039": "The more you use a weapon, the more of a feel you get for it. Eventually, it gets so it's almost a part of your body...",
  "f040": "Sometimes a single word to your comrades can change the course of a battle... Wow, Boss, you always see things the rest of us don't.",
  "f041": "You're never too busy to attend a briefing! See, Boss? I got it memorized!",
  "f042": "Sir, I like the M16A1 for its low recoil. What's your favorite weapon, Boss?",
  "f043": "You ever sneak up behind an enemy and ZAP 'em with the stun rod? Gives me the shivers every time!",
  "f044": "Life is all about experience! Come to think of it, I guess that goes for drills, too... ugghh, I hate drills...",
  "f045": "Do you believe in fate? Right now, I think I could.",
  "f046": "I believe in you, Boss. Under your command, gender means nothing.",
  "f047": "I just don't know what I'm good at... Can you tell what my skills are, Boss?",
  "f048": "Staring at me's not going to do anything. Penny for your thoughts, sir.",
  "f049": "Orders, Boss?",
  "f050": "I usually hate doing things for other people. But for you, Boss, I'll do anything.",
  "f051": "I always saw myself as a lone wolf. But I guess people's values can change pretty quick. Lord knows I've changed since I came here.",
  "f052": "I'm not the type to follow orders. Unless you're giving them, Boss.",
  "f053": "I'm burning for some action! Got a mission for me?",
  "f054": "I like it here. It's a nice place.",
  "f055": "Do you believe in horoscopes? Me, I only believe in you.",
  "f056": "What do you see in those eyes of yours...? Sorry, didn't mean to get personal.",
  "f057": "When things get tough, think of me. That might ease the pain a little.",
  "f058": "I can be kind of stubborn, but I'm a survivor, too.",
  "f059": "People say I'm a little CRRRRRAZY...",
  "f060": "I heard you're scared of vampires - is that true? Aww... that's actually kind of cute, Boss!",
  "f061": "Don't underestimate me because I'm a woman. We ladies can fight in ways you men can't!",
  "f062": "Oh... Boss...",
  "f063": "Give me a mission, and I'll do everything I can to get it done!",
  "f064": "Boss! Send me out into the field! I'm going crazy just sitting around here! My legs are starting to cramp up!",
  "f065": "Boss! Send me into the field! I promise I'll come back alive!",
  "f066": "Comrade-in-stealth... it's got a nice ring to it.",
  "f067": "You know, Commander Miller is actually kind of cute when he takes off those sunglasses.",
  "f068": "My hobby is gardening.",
  "m001": "I'm your man! Give me an order, I'll get it done!",
  "m002": "I am hyped!! Let's do this!!!",
  "m003": "Need a...helping hand?",
  "m004": "I left some of my buddies behind on the last battlefield...\nYou gonna give me the chance to make it up to them here?",
  "m005": "I got a daughter. She's going to be 12 next year. I have to make it out of this alive!",
  "m006": "I used to be a sailor. Best pair of eyes on the seas!\nNeed someone who can see things a mile off?",
  "m007": "I'm a weapons technician.\nYou say weapons kill people?  I say they're needed to protect people.",
  "m008": "Give me a mission, Boss!",
  "m009": "I'm a martial arts expert - I know Combat Sambo and I'm a fifth degree black belt in karate!\nCQC? This I gotta see!",
  "m010": "My grandpa was a mechanic. I can take an air-cooled engine apart in five minutes flat!",
  "m011": "I got back from Vietnam and found I had no place to call home anymore...\nMind if I stick with you guys for a while?",
  "m012": "I went through hell in 'Nam... I'm ready for anything!",
  "m013": "I was an Officer Candidate. Not much combat experience, but I speak seven languages.\nThere's got to be some use for me here.",
  "m014": "Need a dentist?\nBack in my dad's day, every army battalion had its own dentist.",
  "m015": "Costa Rica is full of swamps... make sure we got a good supply of dry socks.\nThe last thing we need are fungal infections.",
  "m016": "You're good. Better than I expected.",
  "m017": "As much as I hate to say it, it's war that gives us our greatest breakthroughs in science and technology.",
  "m018": "I know it takes more than weapons to make us strong and all, but at least give us some decent gear, alright? ",
  "m019": "Heh... Imagine. If only we had a guy like you running the country...\nMaybe my village wouldn't have been burned to the ground.",
  "m020": "You look like you'll come in handy. I guess I'll stick around and help you out.",
  "m021": "Gotta get your hands dirty to win a war...\nYou know what I'm talking about, right?",
  "m022": "We can do better than this.",
  "m023": "You? A sneaking master?! Are you kidding me?\nI can smell the gunpowder on you a mile away!",
  "m024": "I can smell it... The smell of blood...  Lots of blood...",
  "m025": "Ready when you are, Boss.",
  "m026": "Well, I've earned MY check... Time for a nap...",
  "m027": "Guns kill people? Bro, sometimes guns are the only things that save lives.",
  "m028": "I used to be a world-class gymnast, you know.\n'Course, when it comes to a war, pride and glory don't mean a hell of a lot.",
  "m029": "When this fight's over, I'm gonna go back home and find myself a wife...",
  "m030": "I still haven't made up my mind about you yet.",
  "m031": "I can tell that you're not in this 'cause you like the smell of hot lead. Am I right?",
  "m032": "Just so you know, the more praise I get, the better I do.",
  "m033": "Drinks later? It's on me.",
  "m034": "Think you can take advantage of my skills?",
  "m035": "Balls to the wall, boys!",
  "m036": "Let's see, my horoscope says today's going to be... OK, I guess.",
  "m037": "C'mon, give me a mission! My rifle's getting all rusty!",
  "m038": "Things are never better than when they're ordinary.",
  "m039": "I... I don't wanna fight. I wanna be a cook.",
  "m040": "Hey Boss, at dinner do you eat your favorite food first, or save it for last?",
  "m041": "You're like a knife out of its sheath, you know that?",
  "m042": "My muscles never fail me.",
  "m043": "(I'm too shy to talk to people... I believe in you, Boss...)",
  "m044": "We're gonna make a name for ourselves!",
  "m045": "Look, Boss! I caught a male Elephant Beetle, the world's heaviest insect!",
  "m046": "Happy to be on board with you, Boss.",
  "m047": "It's good to have comrades...especially on the battlefield.",
  "m048": "Don't worry, I got your back!",
  "m049": "Boss, if there's anything I can do to help make our technology better, I'll do it.",
  "m050": "Good eats everyday!",
  "m051": "You want to know how to raise morale around here?\nSimple! Give us letters from our folks. And hot meals - can't fight on an empty stomach!",
  "m052": "It's a real honor fighting with you...",
  "m053": "Sometimes, I get to thinking. What is human life in the face of truly great scientific research?",
  "m054": "Welcome back! I made something new for dinner today - want to try some?",
  "m055": "You're one smart customer, man!",
  "m056": "I'm former SAS... what you think I'm B.S.-ing you?",
  "m057": "I'm proud to be counted as one of your comrades, Boss!",
  "m058": "I...I can't believe I'm actually meeting you in person, Boss!",
  "m059": "(Just between you and me, I'm the guy who keeps MSF together...)",
  "m060": "You stay here. I'll have this next mission wrapped up in no time.",
  "m061": "This mission's nothing. I could do it with my eyes closed.",
  "m062": "Boss, I've been meaning to tell you... nah, forget it. It's nothing.",
  "m063": "I owe you one. Guess I better come with you.",
  "m064": "Who'd have thought being stealthy could be such a thrill...",
  "m065": "I actually kind of like the way you fight.",
  "m066": "I'll show you how to get it done the smart way!\nThat's the kind of guy I am!",
  "m067": "Back home, I'm a pretty well-known journalist.\nI'm going to write your story and tell everybody how you lived.",
  "m068": "You look prettier every time I see you.",
  "m069": "Wish I could have met you sooner...",
  "m070": "Listen, I never actually hated you...",
  "m071": "It's all about the food. Give most guys a good meal and they won't complain. ",
  "m072": "When this battle's over, I'm going to get my life together...",
  "m073": "Don't worry, my cooking's 100% safe for human consumption.",
  "m074": "I've...never been in a real fight before...",
  "m075": "If we met under different circumstances, I bet we could have been good friends.",
  "m076": "Eureka! My research is going to blow your mind, Boss!",
  "m077": "I just finished an incredible story! Could you read it and let me know what you think?",
  "m078": "Before I became a mercenary, I was a doctor. Would you like to try this new drug I'm working on?",
  "m079": "Quitting smoking is easy! Why, I've quit 20 times myself.",
  "m080": "I can't promise you I won't do bad things, but\nI will promise you this: I'll never make us look bad.",
  "m081": "Well now, looks like my boys gave you some trouble. Sorry 'bout that.\nI'll make it up to you. Here, take this.",
  "m082": "Let's use our heads on this one.",
  "m083": "Everybody can do something, but nobody can do everything.\nWe'll do the things you can't.\nAnd we need you to do the things we can't!",
  "m084": "Ah, Boss, glad you're here. We were short one guy tonight.\nCare to join us for a little game?",
  "m085": "You want me to forget last night...? Too late. It's all in my diary now.",
  "m086": "You're our greatest hope, Boss!\nWe won't let anybody take our hope from us!\nI may not be strong, but I'll fight till the end!",
  "m087": "What the hell, let's have fun out there!",
  "m088": "Ohhh... my stomach...",
  "m089": "When we're all done here, I think I'm going to start my own business.",
  "m090": "Kill 'em, let 'em live... it's up to you. Either way, give 'em hell!!",
  "m091": "Awaiting orders, Boss!!",
  "m092": "I'm bringin' home the bacon!",
  "m093": "It's either us or them!\nThat's right. That's ...the way it should be, in a war.",
  "m094": "Sometimes it's good to grab life by the horns.",
  "m095": "Looks like another late night at the office...",
  "m096": "You're number one, Boss. That makes me number two, right?",
  "m097": "198, 199, 200! Oh, hey, Boss, you're just in time!\nI just finished doing 200 stomach crunches!",
  "m098": "For the last time, stop treating me like a rookie!",
  "m099": "I could learn to like this outfit.",
  "m100": "Nothing feeds a developer like the sound of a satisfied user.",
  "m101": "Why do it toda-a-ay? There's always tomorro-o-ow...",
  "m102": "Ahhh, we got a nice big catch today!\nTonight's dinner is gonna be fresh sashimi with cold Japanese sake.",
  "m103": "I love to grill things. My favorite food is stir-fried noodles.\nThose grilled chicken skewers they got in Japan are pretty good, too.",
  "m104": "I'm saving up all the money I make here, so when I get back to the States, I can go to college...",
  "m105": "No need for you to go, Boss... I got this one covered.",
  "m106": "We're not blood related, but we're still family.\nCome back home alive brother. ",
  "m107": "This place can only hold so many bodies. So make sure you bring back the best you can find. At least as good as me.",
  "m108": "A lot of the most talented soldiers out there are in places where you can't recover them the usual way. I know there's gotta be some way to get them, but...",
  "m109": "To get the higher-ranked weapons, you'll need to find the design specs and raise the level of the R&D Team. Guess you got your work cut out for you in the field and at Mother Base...",
  "m110": "From what I've heard, supposedly there's a way to have items and ammo delivered right to you in the middle of a mission...",
  "m111": "Back in my old unit, the commander used to tell us at morning calisthenics: \"Whenever you're in trouble, hit the START button!!\"\nWonder how he's doing these days,",
  "m112": "I-I saw some gigantic footprints in the swamp around El Cenagal...\nY-you think it's a monstruo?",
  "m113": "The other day, out of the blue we got a big box delivered to us.\nNo return address, but it was full of all kinds of good stuff...\nKind of creepy, I know... but I wasn't about to complain!",
  "m114": "For me, there's no greater thrill than seeing your exploits in PLAYER DATA, Boss!",
  "m115": "With word about MSF going around, no wonder there are more volunteers who want to join.",
  "m116": "I swear I saw fireworks last time I was in combat. Do they really make a weapon like that?",
  "m117": "When I fire my weapon, I never aim for the head. Can't recruit 'em if they're dead, after all.",
  "m118": "Some crates are too big to climb alone, but they're no problem if you got a buddy. Maybe that's what friendship is all about.",
  "m119": "If you ever get stuck in a mission, retreating is always an option! Isn't that right?",
  "m120": "Boss! The R&D Team is screwing around! They are playing with the cardboard boxes! What the hell is that?!",
  "m121": "In combat, running out of ammo is a death sentence. Steal some from the enemy if you have to, or call for resupply, or search around the area! Good luck!",
  "m122": "You can't attack while reloading. So find someplace to take cover when you do! That's what's kept me alive all these years.",
  "m123": "Enemy hiding out of sight? Try the night-vision goggles. That's what I do.",
  "m124": "Suppressors don't last forever. Use them enough and they wear out. Best to keep an eye on how long they've got left.",
  "m125": "Whoa, almost screwed up back there... All because I didn't read the intel in the BRIEFING FILES first... You gotta use your brains, not just your brawn.",
  "m126": "They say when you CO-OPS with somebody, you can tell who they regard as the greatest hero they've gone CO-OPS with. ",
  "m127": "I always go into a mission empty-handed. I can always borrow gear from my teammates.",
  "m128": "Flying enemies are weak against explosions. Damage 'em with a missile and it might create an opening... right, Boss?",
  "m129": "The canopies on attack choppers are pretty solid, but you can break though them. It's the only way to get at the pilot inside... But you probably already knew that.",
  "m130": "A helicopter uses its tail rotor to combat counter-torque. In other words, without it the chopper can't fly straight. You could say it's like the chopper's jugular vein.",
  "m131": "My instructor told me when you get up close and personal with the enemy, CQC works better than a rifle! I'm gonna practice every chance I get!",
  "m132": "It's tough to see where you're going in the Ruinas de Xochiquetzal in Central Heredia. I wouldn't trust my eyes too much if I were you...",
  "m133": "The last war I was in, I attached an extra weapon to the barrel of my assault rifle. It's kind of tricky to switch between them, but once you get used to it you'll wonder how you ever got on without it.",
  "m134": "Sneak up behind the enemy and hold 'em up, then make sure you Fulton recover 'em! ...That's how I do it.\nLeave 'em with their hands up for too long and you never know when they're gonna turn their guns on you again.",
  "m135": "Night-vision goggles aren't just useful at night. Foggy jungle, enemy smoke grenade - they come in handy anytime you can't see more than a few feet in front of you.",
  "m136": "If only we had a weapon that let us capture those enemy heavy weapons without hurting them... maybe we could take them back to Mother Base and put them to use...",
  "m137": "Yup... MSF needs all the firepower it can get. Like mechs, for example. Capturing them from the enemy would be quickest. Or, there's the other way...",
  "m138": "There's two basic ways to take on a unit with a mech. Overwhelm them with sheer firepower, or take out the soldiers first and then capture the machine. Decisions, decisions...",
  "m139": "You're not gonna believe this, but... I saw this cat-thing rowing a little boat down by the Caribbean coast! Next time you're on a mission down there, see if you can find it!",
  "m140": "I love UMAs. Monsters, too... you know anybody who knows a lot about rare creatures? I want to pick their brain! Pick it CLEAN!",
  "m141": "I don't care how good they taste, I HATE eating cold rations! If only we could grill 'em up a little... Then I'd be happy.",
  "m142": "Flying weapons are usually pretty noisy. They ought to be easy to find if you've got a Surround Indicator... right, Boss?",
  "m143": "They say there are monsters out there somewhere in this country, and if you hunt one down, you can use it to develop amazing gear. Of course, I don't believe a word of it.",
  "m144": "The fuel tanks on the enemy's heavy weapons are painted red. Seems like that'd be a good place to shoot them.",
  "m145": "Boss, did you know there's some kind of miracle gun that makes the sky do your bidding? Think we could make one here?",
  "m146": "Missile-type weapons are heavy and have low ammo capacity. But they pack the most firepower of any portable weapon. Exactly what you need against heavy weapons.",
  "m147": "Machine guns are powerful and carry a lot of ammo, so they're perfect for taking down mechs. Of course, they're also heavy and tough to handle...",
  "m148": "Sniper rifles are the best for precision long-range shots. A lot of them even fire armor-piercing rounds.",
  "m149": "Submachine guns are easy to aim, and they've got good rapid fire! Plus you can use them with a shield. You just have to get used to the muzzle jump, that's all.",
  "m150": "Did you hear? Somebody said they saw \"God\" inside a truck somewhere...",
  "m151": "Assault rifles are all-around solid weapons in every respect. There's lots of custom parts for them, too, so it's worth doing some R&D...",
  "m152": "Shotguns are AWESOME! They can blow away just about anything in one shot. Only problem is they got short range and low ammo.",
  "m153": "Handguns have short range and low firepower, but they've got great accuracy at close range and high-caliber ammo that stops targets in their tracks. And if you know when and how to use them, you can conserve your rifle ammo... That's a quote from the Boss. I learned it by heart!",
  "m154": "The two things you gotta remember for sniper rifles are \"crouch\" and \"aim.\" I guess 'cause it makes your hands shake less!",
  "m155": "If you're using a one-handed weapon, you can equip a shield at the same time. And when it's not on your arm, it'll protect your back... isn't that what you said, Boss?",
  "m156": "Handguns are great for indoors and in tight spaces... 'cause they're easy to aim.",
  "m157": "You're telling me armor-piercing rounds go through shields and helmets?! Man, talk about punch.",
  "m158": "Large-caliber handguns are the best tool for stopping the enemy from acting. AND they let you use CQC at the same time. If you find yourself surrounded, try going with a handgun.",
  "m159": "You ever hear of these \"battle cries\" that make amazing things happen sometimes when you say them? Crazy, huh?",
  "m160": "You know what I like about working for you, Boss? You know how to complete a mission without hurting anybody, without them even knowing you're there.",
  "m161": "I thought my gear felt a little heavy... Turns out my guns alone weighed 20 pounds! No wonder my PSYCHE decreased. Heavier isn't always better, I guess.",
  "m162": "Back when I was a rookie, I used to spray my assault rifle all over the place and waste ammo... You gotta stay focused, aim, and be smart with your trigger finger, fire in small bursts. It's not how many shots you fire, it's how many hit the target. I wish I'd realized that sooner... ",
  "m163": "Timing is everything in consecutive CQC, y'know. Gotta be cool, press the button at just the right time...",
  "m164": "Boss, if you find me lying face down on the battlefield you gotta revive me! Uh, but no mouth-to-mouth, please!",
  "m165": "In training I got CQC-thrown against a wall and got knocked out. Felt like it hurt at least twice as bad as a usual throw, too...",
  "m166": "I bet even the toughest missions wouldn't be so bad for a two-man cell!  I'm gonna go look for somebody to team up and fight with!",
  "m167": "Hey Boss, can you teach me how to reload?\n...Ahh, so that's it! Just push the Action Button with the weapon equipped! Thanks a bunch, Boss!",
  "m168": "Reloading leaves you temporarily vulnerable. Timing your reloads is just as crucial as timing your shots. Isn't it, Boss?",
  "m169": "Hey Boss! Thanks for always listening to us grunts. I mean, even we can teach you something once in a while. Right?!",
  "m170": "Chicks dig a man who smells like success!",
  "m171": "Ahh, I get it... GMP is the sum total of MSF's income... the same way GNP expresses a country's total income...",
  "m172": "If the next mission looks too tough for you, take a break and focus on recruiting or developing weapons... Yeah, that's right, never be in too big of a hurry!",
  "m173": "In MISSION PREP we have to be careful not just about what gear we bring, but what uniform we wear. Right, Boss?",
  "m174": "Check out the MAP to see where the exits are. Pretty handy if you ever get lost.",
  "m175": "I think we could do a lot better job if we had stronger guns. We oughta get working on developing some new weapons!",
  "m176": "I think we could do a lot better job if we had stronger guns. We oughta get working on developing some new weapons!",
  "m177": "My great-grandpa used to tell me, \"Sonny, bananas are good for more than just eatin'.\"",
  "m178": "Boss, let me deploy on EXTRA OPS! I can handle it!",
  "m179": "I've seen female soldiers being held prisoner. But I wasn't able to save them...",
  "m180": "If a target's helmet is getting in the way, shoot it off with a bullet. It works best if you do it before they notice you. Right?",
  "m181": "How fast a tranq dart works depends on where it hits... Ack, what the--? Unnhh... ZZZZ...",
  "m182": "You gotta turn away as soon as you throw a stun grenade or you'll get stunned, too... Thanks for the tip, Boss!",
  "m183": "One day, we'll have the science to turn a man invisible. And when that day comes... heh heh.",
  "m184": "When you're using a sniper rifle, slow down, take a deep breath, and concentrate. It's true... you can actually feel your hands get steadier!",
  "m185": "A man's got to eat to live. If you forget to bring food along on a mission, you better be damn good...",
  "m186": "Man, I could go for a nice cold soda... That'd really hit the spot...",
  "m187": "The Analyzer tells you how good a soldier is, so you can pick the best ones to recruit... That's the most logical way to go about it.",
  "m188": "I like the M10... It's got a decent rate of fire and you can AUTO AIM it from a good distance.",
  "m189": "My dream is to invent a weapon that lets you Fulton recover somebody from a distance...",
  "m190": "So what if you get knocked out? A few good smacks and you'll wake right up!",
  "m191": "Every mech has a weakness, no matter how big it is... And I intend to find it!",
  "m192": "I heard there's a suit that makes your footsteps almost silent. Imagine how useful that'd be for sneaking up on people from behind.",
  "m193": "You ever try running around lugging a big, heavy weapon? It ain't easy. Ain't fast, either...",
  "m194": "With a high enough morale, a soldier can do things he never thought possible. Me, I'm ready to rock!",
  "m195": "The golden rule of staff management is, let people do what they do best. So, where do you need me to go?",
  "m196": "Comrades, lets keep communication tight!  What...? You can't find the right words!? Well then make sure you set your \"CO-OPS COMM\" in \"MISSION PREP\" so it doesn't happen again!",
  "m197": "You know when you get a package, and it's exactly what you needed the most? I always get a little misty when that happens...",
  "m198": "If I ever manage to get a girlfriend, I wanna take her inside a cardboard box... and spend some quality time together...",
  "m199": "I wonder if you could use a cardboard box as a step to get up to places you couldn't usually reach by yourself...",
  "m200": "I coulda sworn I saw a guy who looked just like me... Hm. Must have been a coincidence.",
  "m201": "It's nice to have a place to come back home to. I'm glad I joined up with you.",
  "m202": "The food ain't too bad here. 'Course, it's nothing like my ma's.",
  "m203": "I got a wife and daughter back in my home country. Gotta work hard so they can eat.",
  "m204": "Boss, MSF is more than just you. Don't forget that.",
  "m205": "I'm saving up my pay to buy a house and get married!",
  "m206": "Man... I'm sick of people treating me like a rookie! Ugh...",
  "m207": "Yesterday's enemy is today's ally...",
  "m208": "You wanna know what's the most powerful weapon known to man? A good poker face.",
  "m209": "Need some luck? Stick with me and maybe some of mine will rub off.",
  "m210": "This place is full of morons... That's why I love it so much.",
  "m211": "Call me... ah, forget it. Call me whatever you want.",
  "m212": "Check out this tattoo. Each one of these stars stands for a battlefield I've slogged through... they're actually just stickers, but still...",
  "m213": "Support is just as crucial as combat! Anything you need, let me know!",
  "m214": "I need a mission that REALLY gets me motivated...",
  "m215": "The bacon in the mess hall was extra crispy this morning. I feel like I can do anything today.",
  "m216": "Boss! That magazine I lent you before the last mission. Can I have it--what?! You left it out there?! I hadn't finished reading it!!",
  "m217": "Give me an order, Boss. I'm not what you'd call a self-starter.",
  "m218": "I got two yolks in my egg this morning. So I'm gonna work twice as hard today! ...Or at least complain half as much!",
  "m219": "Boss! Send me into battle! I can handle it!",
  "m220": "I can never seem to balance work and pleasure. 'Cause whatever I'm working on turns into pleasure.",
  "m221": "Hey Boss, let's get as many new guys as we can and make MSF into something REAL big!",
  "m222": "We got skills, too, Boss! Take a look and see!",
  "m223": "When's the party gonna start, amigo?",
  "m224": "Wish I could see the Loch Ness Monster or Quetzalcoatl once in my life...",
  "m225": "Boss! He says there's no Santa Claus! Santa's real, isn't he?!",
  "m226": "Boss! He says Santa Claus is real! There's no such thing as Santa, is there?!",
  "m227": "I may not look it, but I'm turning 48 this year.",
  "m228": "I'll be honest. I don't think I'm good enough. But I want to be. And I'm training hard.",
  "m229": "Give yourself a little break once in a while, Boss.",
  "m230": "I like you.",
  "m231": "Everything about this place is hot, hot. The weather, the work...",
  "m232": "I'm a mountain boy. All this water, and boats and stuff... erk. Give me a mission, quick...",
  "m233": "It's an honor to serve under a hero like you.",
  "m234": "I can't sleep at night unless I clean my gun once a day. I'm itching for an overhaul...",
  "m235": "Thanks for the Costa Rican coffee. Best I ever tasted.",
  "m236": "My wife was always good to me. Guess that's what \"love\" is.",
  "m237": "If I die, we'll meet again in the next life. As comrades.",
  "m238": "One thing I've realized since I got here - there's all kinds of people in this world.",
  "m239": "Take a look at these guns. I was the arm wrestling champion of my hometown two years running. And runner-up the year before that, and champion the year before THAT.",
  "m240": "Can we have curry on Friday? I love curry!",
  "m241": "I used to be in the army, but the government sold us out. Is there anything worth risking your life for anymore?",
  "m242": "You stay here too long, you start losing track of what day it is.",
  "m243": "Ready for duty, chief!",
  "m244": "I like to CALL people on the radio while I'm on a mission. It's a good way to get useful info, and it reminds me I'm not alone out there.",
  "m245": "I'm a slave to fashion. I collect T-shirts in my spare time.",
  "m246": "It's important to know what to wear, even on the battlefield. The right clothes for the right occasion.",
  "m247": "Listen to the waves. Smell the fresh sea air. Soothing, isn't it...",
  "m248": "I got a buddy named Johnny. You know him?",
  "m249": "You don't want to over-grill a ration. But if you're just gonna lightly toast it, I say you're better off not grilling at all.",
  "m250": "Hello there! Remember me? We met a while back. Thanks for helping me out then...",
  "m251": "I'm no good with people. Please look after me.",
  "m252": "I was just thinking the same thing as you, Boss",
  "m253": "I can't believe you took me in, Boss... I'll do my best not to disappoint, but I'd totally understand if you have to sack me.",
  "m254": "Let's put our heads together and make Mother Base grow!",
  "m255": "If you want to create a change in time, don't blindly abide by society's rules. Be able to evaluate what is right and wrong on your own...   Right Boss? ",
  "m256": "You sure love your cardboard boxes, Boss... I love 'em too.",
  "m257": "I got a daughter back home. Haven't seen her in years...",
  "m258": "When this battle's over, I'm gonna go home and be a shrimper. Me and my buddies are gonna pitch in an buy a big boat!",
  "m259": "I cut my bangs too short.",
  "m260": "Hah, hah, hah, hah... nothing like pumping some iron!",
  "m261": "You ever tried chorizo? It's a Mexican sausage. Good stuff, especially when you fry it up with eggs!",
  "m262": "You a cat person or a dog person, Boss? Me, I'm a cat person... Ah... AH... ACHOO! Too bad I'm also allergic to them."
});
const other = Object.freeze({
  "0x01487A": "My name is Paz, and I'll do anything to protect my namesake.",
  "0x0B58FC": "70% of my existence is made of movies.\nIt is up to you to decide what to do with the remaining 30%. ",
  "0x255CF9": "My father worked on the Manhattan Project.\nIn a lifetime of research, he produced two things. The illusion of peace through deterrence...\nAnd me and my useless legs.\nOne way or the other, I had to face up to the nukes.",
  "0x37618C": " I am Vladimir Zadornov, and Vladimir means \"ruler of peace.\"",
  "0x552CB3": "If you see any UMAs, you tell me, OK?\nLike ancient dinosaurs and rare monsters and stuff.\nWhen I grow up, I wanna be a hunter.",
  "0x580DAA": "We abandoned our countries. Nothing more.",
  "0x6747B0": "Why was a legendary hero forced to betray her country? Why was she targeted for assassination by you, her most beloved disciple?\nI've no use for fabrications.\nI want the truth... The Boss's last will. ",
  "0x6ADE44": "(不要)「………」（大塚さん（声優）一言コメント仮）",
  "0x72AE4F": "I've been thinking of giving up on studying birds and learning to fly myself.\n\nWant to hear my quetzal call?",
  "0x74AF6C": "(不要)「………」（杉田さん（声優）一言コメント仮）",
  "0xB73990": "We're not mercenaries. We're not a foreign legion. MSF's a business. A new kind of business.",
  "0xE3D5FB": "....",
  "0xF1C147": "You need a special talent to become cacique. It takes someone great to unite all of las compas."
});
function preview(seed, gender) {
 if (!Number.isInteger(seed) || seed < 0 || seed > 0xFFFFFFFF) throw Error('Invalid uint32 quote seed');
 if (gender !== 'Male' && gender !== 'Female') throw Error('Invalid quote gender');
 const count = gender === 'Male' ? 262 : 68;
 const index = seed === 0 ? 0 : seed % count + 1;
 const key = (gender === 'Male' ? 'm' : 'f') + String(index).padStart(3,'0');
 return Object.freeze({seed, key, text:ordinary[key] ?? other['0xE3D5FB'],
  language:'en', readOnly:true, previewKind:'base-quote',
  note:'English base quote; in-game special-character or status overrides may replace it.'});
}
global.PWSEQuotes = Object.freeze({ordinary, other, preview});
})(window);
